#!/usr/bin/env python3
"""Export a final PPTX through LibreOffice from a generated authoring deck."""

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild a generated PPTX package with LibreOffice before delivery."
    )
    parser.add_argument("input", type=Path, help="Source PPTX generated by PptxGenJS.")
    parser.add_argument(
        "--output",
        type=Path,
        help="Final PPTX path. Defaults to overwriting the input file.",
    )
    args = parser.parse_args()

    input_path = args.input.expanduser().resolve()
    output_path = (args.output or input_path).expanduser().resolve()

    if input_path.suffix.lower() != ".pptx":
        raise ValueError(f"Expected a .pptx file, got: {input_path}")
    if not input_path.exists():
        raise FileNotFoundError(input_path)

    with tempfile.TemporaryDirectory(prefix="pptx_windows_export_profile_") as profile:
        with tempfile.TemporaryDirectory(prefix="pptx_windows_export_out_") as out_dir:
            cmd = [
                "soffice",
                f"-env:UserInstallation=file://{profile}",
                "--headless",
                "--norestore",
                "--invisible",
                "--convert-to",
                "pptx",
                "--outdir",
                out_dir,
                str(input_path),
            ]
            subprocess.run(cmd, check=True)

            produced = Path(out_dir) / input_path.name
            if not produced.exists():
                raise FileNotFoundError(f"LibreOffice did not produce {produced}")

            output_path.parent.mkdir(parents=True, exist_ok=True)
            if output_path == input_path:
                shutil.move(str(produced), str(input_path))
            else:
                shutil.copy2(produced, output_path)

    print(f"Final PPTX exported: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
